### ISSUE TITLE
using dall-e?

### ISSUE THREAD

**Issue by titaniumbones** [gregoryg/AIPIHKAL#1]
Hi, thank you for this very cool resource.  I'm not quite sure how to use the image prompt, though.   I know dall-e  has a separate endpoint, and I don't see anything in either your or karthint's gptel-openai that references it.  Am I missing something obvious?

Thanks again!

**Comment by gregoryg** [comment]
Hi @titaniumbones !  The Midjourney prompt is actually just a way to get a language model to craft long detailed prompts for a separate image generator such as Dall-E or Midjourney.  It's a tangled web!

The gptel package is only for text LLMs, not image generators.

**Comment by titaniumbones** [comment]
thanks for the clarification, I understand now!
